### ISSUE TITLE
Advent of CodSpeed runs not working

### ISSUE THREAD

**Issue by adriencaccia** [DarthGandalf/advent-of-code#84]
Hey @DarthGandalf, I saw your comment on Reddit and [answered it there](https://old.reddit.com/r/adventofcode/comments/1h3qahp/advent_of_codspeed_a_rust_performance_leaderboard/m0dbaaw/).

I paste it here also so that you are notified before today's run:
>It seems that your crate cannot be found, as you can see in the run from yesterday: https://github.com/CodSpeedHQ/Advent/actions/runs/12144514315/job/33864093312
>It might be because your repository is not a workspace. You can test the runner by following these instructions. If you need to have some values changed (name of the repo, name of the package, etc...), you can open an issue in https://github.com/CodSpeedHQ/Advent and I will sort you out!

**Comment by DarthGandalf** [comment]
Thanks, I've actually run the test from https://github.com/CodSpeedHQ/Advent/tree/main/rust-runner locally even before opening my PR. It works fine there.

```
$ cargo codspeed run
   Collected 2 benchmark suite(s) to run
     Running rust-runner bench_part1
Harness: codspeed-criterion-compat v2.7.2
NOTICE: codspeed is enabled, but no performance measurement will be made since it's running in an unknown environment.
Checked: rust-runner/bench_part1.rs::benches::bench_part1::day1::part1
        Done running bench_part1
     Running rust-runner bench_part2
Harness: codspeed-criterion-compat v2.7.2
NOTICE: codspeed is enabled, but no performance measurement will be made since it's running in an unknown environment.
Checked: rust-runner/bench_part2.rs::benches::bench_part2::day1::part2
        Done running bench_part2
    Finished running 2 benchmark suite(s)
```

Here's my local run of the command which failed in that log:

```
$ cargo add --git https://github.com/DarthGandalf/advent-of-code aoc2024 --rename solution
    Updating git repository `https://github.com/DarthGandalf/advent-of-code`
      Adding aoc2024 (git) to dependencies
    Updating git repository `https://github.com/DarthGandalf/advent-of-code`
    Updating crates.io index
     Locking 8 packages to latest compatible versions
      Adding anyhow v1.0.94
      Adding aoc-runner v0.3.0
      Adding aoc-runner-derive v0.3.0
      Adding aoc-runner-internal v0.1.0
      Adding aoc2024 v0.1.0 (https://github.com/DarthGandalf/advent-of-code#6294a847)
      Adding minimal-lexical v0.2.1
      Adding nom v7.1.3
      Adding syn v1.0.109


```

**Comment by adriencaccia** [comment]
When I run the following command in the `rust-runner` directory, it fails:

```
$ cargo add --git https://github.com/DarthGandalf/advent-of-code aoc2024 --rename solution
     Updating git repository `https://github.com/DarthGandalf/advent-of-code`
  error: the crate `aoc2024@https://github.com/DarthGandalf/advent-of-code` could not be found at `https://github.com/DarthGandalf/advent-of-code`
```

I do not understand how it works on your side 🤔 
Maybe there is a permissions issue?

**Comment by DarthGandalf** [comment]
Apparently your cargo is too old.

I can reproduce the error on cargo 1.81.0 (2dbb1af80 2024-08-20)

It works on cargo 1.84.0-nightly (4a2d8dc63 2024-11-09)

**Comment by adriencaccia** [comment]
Thanks for pointing it out, we noticed that we were not using the toolchain defined by the users to do the `cargo add ...` command.
We will fix that!

**Comment by DarthGandalf** [comment]
Thanks!
