### ISSUE TITLE
Repo not automatically picked up on Advent of CodSpeed

### ISSUE THREAD

**Issue by adriencaccia** [DarthGandalf/advent-of-code#85]
Hey @DarthGandalf, we made an [update in `CodSpeedHQ/Advent`](https://github.com/CodSpeedHQ/Advent/commit/04d7b89ca3883b90d86fc7ad498d60658e4dd0e1#diff-12baa4ff56d798b5d9da491e57292292bfe48c53175d85e422acca2717eb28d9R59) to only run repos where the `dayN` module is present.

Unfortunately, it does not work in a monorepo without a proper cargo workspace, so each day I had to manually rerun your repo. Could you add `Cargo.toml` at the root of your repo so that it will be picked up automatically? You can see how another participant with the same issue fixed it here: https://github.com/jpverkamp/advent-of-code/pull/20

Thanks a lot, and good luck for the rest of the event!

**Comment by DarthGandalf** [comment]
Ah, thanks!

I'd rather not have a shared Cargo.lock file between different years.

What about something like https://github.com/CodSpeedHQ/Advent/pull/209 ? (completely untested)

**Comment by art049** [comment]
We ended up changing the way we check for the solution with this: https://github.com/CodSpeedHQ/Advent/commit/26e3e7bebdb7adfdcd584aabd926c468c96006be

**Comment by DarthGandalf** [comment]
Cool
